Attempted fix for no pylint output

diff --git a/.github/workflows/Static_Analysis.yml b/.github/workflows/Static_Analysis.yml
--- a/.github/workflows/Static_Analysis.yml
+++ b/.github/workflows/Static_Analysis.yml
@@ -17,29 +17,30 @@ jobs:
       - name: Checkout Repo
         uses: actions/checkout@v3
 
-      - name: Setup Python
-        uses: actions/setup-python@v4.4.0
-        with:
-          python-version: '3.10'
+      #- name: Setup Python
+       # uses: actions/setup-python@v4.4.0
+        #with:
+         # python-version: '3.10'
 
       - name: Install Prospector
         run: pip install prospector
+
       - name: Setup Pylint annotations
         uses: rodrigo-nogues/pylint-annotations@v1
-        
+
       - name: Run Prospector
         run: |
           #Outputs the pylint report to project root
           prospector --full-pep8 --output-format pylint:prospector_report
       
-      - name: Convert test results to Github Annotations
-        uses: mikepenz/action-junit-report@v3
+      #- name: Convert test results to Github Annotations
+        #uses: mikepenz/action-junit-report@v3
         #Use success()||failure() to allow for manual cancellation of an action (see docs)
-        if: success()||failure()
-        with:
+        #if: success()||failure()
+        #with:
           #Report in project root
-          report_paths: ./prospector_report.xml
-          check_name: "Prospector Analysis Report"
+          #report_paths: ./prospector_report.xml
+          #check_name: "Prospector Analysis Report"
 
           
 
