fix: format comments

diff --git a/.github/workflows/unit_tests.yml b/.github/workflows/unit_tests.yml
--- a/.github/workflows/unit_tests.yml
+++ b/.github/workflows/unit_tests.yml
@@ -21,7 +21,7 @@ jobs:
         uses: actions/setup-python@v4.4.0
         with:
           python-version: '3.7'
-          cache: 'pip' #Cache dependencies
+          cache: 'pip' # Cache dependencies
           cache-dependency-path: '**/pyproject.toml'
 
       - name: Install pip-tools and generate requirements.txt
@@ -37,15 +37,15 @@ jobs:
       - name: Install Pytest
         run: pip install pytest
 
-        #Pytest generates an XML report
+        # Pytest generates an XML report
       - name: Execute tests
         run: |
          python -m pytest ./truelearn/tests --junitxml=unit_test_report.xml -v
 
-        #Convert the XML report to GitHub annotations
+        # Convert the XML report to GitHub annotations
       - name: Convert test results to Github Annotations
         uses: mikepenz/action-junit-report@v3
-        #Use success()||failure() to allow for manual cancellation of an action (see docs)
+        # Use success()||failure() to allow for manual cancellation of an action (see docs)
         if: success()||failure()
         with:
           report_paths: unit_test_report.xml
